### ISSUE TITLE
Update title text in onBackPressed() function

### ISSUE THREAD

**Issue by gouravkhunger** [gouravkhunger/QuotesApp#1]
Check the 78th line in the [`QuotesActivity.kt`](https://github.com/gouravkhunger/QuotesApp/blob/main/app/src/main/java/com/github/gouravkhunger/quotesapp/ui/QuotesActivity.kt#L78) file.

When someone presses the Back button, then the title is updated. But it is not updated in the [`onBackPressed()`](https://github.com/gouravkhunger/QuotesApp/blob/main/app/src/main/java/com/github/gouravkhunger/quotesapp/ui/QuotesActivity.kt#L90) function in the same activity.

This is a one-line fix that can be solved by adding:

```kotlin
activity_title.text = resources.getText(R.string.app_name)
```

inside the `if` condition in the function.

The issue is targeted at beginners participating in the Hacktoberfest, so please let me know if someone is interested!

**Comment by CH1NRU5T** [comment]
May I try to solve this issue?

**Comment by Kushagra-Jain99** [comment]
I want to work on this issue, this is my first hacktoberfest and first PR so it would be great if you assign me

**Comment by gouravkhunger** [comment]
Hey @CH1NRU5T I think I think I should assign this to complete newbies in Android dev. Maybe you can work on another PR, like updating the dependencies or fixing some other bugs, I will add some intermediate issues I am aware of in sometime. Please watch this repo for changes.

I am assigning this task to @Kushagra-Jain99 for now.

**Comment by CH1NRU5T** [comment]
For sure :)
