### ISSUE TITLE
v2.1.0 added a bunch of trackers and other proprietary elements

### ISSUE THREAD

**Issue by IzzySoft** [gouravkhunger/QuotesApp#14]
I've just noticed that v2.1.0 added a couple of trackers and other proprietary elements, effectively making your app no longer FOSS. Was that intended?

* Firebase Analytics
* Crashlytics
* GMS
* Firebase Core

These also increased the APK size by about 1.5 MB. Your changelog lists those as "features" – us privacy folks rather call them Anti-Features. For transparency reasons, the [listing of your app in my repo](https://apt.izzysoft.de/fdroid/index/apk/com.github.gouravkhunger.quotesapp) will have to reflect this.

I have no idea why a quotes app would need cloud messaging; but if you feel that needed, there are [alternatives](https://gitlab.com/-/snippets/1896503#push) which are more privacy friendly. Same for [analytics and other Firebase features](https://gitlab.com/-/snippets/1896503#firebase-per-se). So should you make the switch (which I'd strongly recommend) or otherwise remove those proprietary components again, those anti-feature markings can be removed again as well. Thanks a lot for caring!

**Comment by gouravkhunger** [comment]
Hi @IzzySoft, I am really glad to see that you list my app in your repo!

I added firebase analytics and crashlytics to get a gist of user behaviour and insights on how many people use the app, I was fixing some bugs and thought to add these too.

But I agree to your points, open source apps should be privacy focussed and I shouldn't be gathering information without user consent.

Please expect to see `v2.1.1` within a day or two where I will remove the firebase integration altogether. I also agree that a basic QuotesApp shouldn't be needing these. I'll also fix the other Anti-Features listed on your repo.

Thanks for taking time to express your concern, this means a lot to me :D

**Comment by IzzySoft** [comment]
Thanks a lot, Gourav – TBH, that's more than I was hoping for, so :bow: – and :crossed_fingers: for your fixes going lightly!

As pointed out: be welcome to use my snippet for ideas on such things. For notifications, we'd all love to see more apps supporting @UnifiedPush for example (the more apps supporting it, the more sense it makes for users to set up a provider of their choice with their devices). And also I'm glad that alternatives exist for almost all that's needed, like those analytic libs or even replacements for other Firebase functionality. So where it makes sense, take your pick from that list!

Looking forward to your next release then. By removing the two analytics components, my updater should inform me that I need to take a look (it won't do so for NonFreeNet, as that's an anti-feature not only triggered by libraries, for example – but then I'll see that along when checking). Should the AFs not be removed within 2 days after your release was pulled, feel free to send me a reminder.

PS: If you wish, feel free to grab [a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link to your app's presence in my repo from your Readme :smiley: There are 2 to choose from (or use both), one is a static image – the other one also shows which version is currently the latest listed in my repo.

**Comment by gouravkhunger** [comment]
Thanks for the privacy-friendly alternative tools list 😄

I'll try to use them whenever possible.

I've published [v2.1.1](https://github.com/gouravkhunger/QuotesApp/releases/tag/2.1.1) with the fixes. Also added the new quote of the day feature, as I am learning WorkManager and it was a good situation where I could make use of it.

And also added the badge to README :)

Thanks for your feedback!

**Comment by IzzySoft** [comment]
Thanks a lot! My updater already notified me, and I've removed all anti-features except the NonFreeNet (due to the site the quotes are pulled from: their licensing is free as in "free beer", but not FOSS).

Thanks for adding the badge – nice to see the versioned one used again, so I see it was worth implementing that API :smiley:

Glad I was able to help out – wishing the best for your project!

**Comment by gouravkhunger** [comment]
Hey @IzzySoft the anti features are not updated for me 🤔 

<img width="948" alt="image" src="https://user-images.githubusercontent.com/46792249/158394977-3604ff14-381d-41b5-a040-7f4431eed383.png">

**Comment by IzzySoft** [comment]
You've looked to early. Daily sync is around 19:00 UTC, so that happened only about an hour ago. Please check again :wink:

**Comment by gouravkhunger** [comment]
Oh got it! Thank you :)

I'm closing this issue now. If you need to report anything, feel free to open a new issue anytime.

And if possible, please do star this repo to show support 😄
