### ISSUE TITLE
SelfUpdater

### ISSUE THREAD

**Issue by IzzySoft** [gouravkhunger/QuotesApp#22]
Hi @gouravkhunger, I don't know if you still maintain this app – but it seems to include a SelfUpdater. Which is against the [IzzyOnDroid App Inclusion Policy](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Inclusion-Policy). Is that updater opt-in? Does it make the implications clear (e.g. that it bypasses the security checks performed in the IzzyOnDroid repo)? A quick scan of the code seems to say "no to all": it looks like the check is performed automatically, and that there's no setting to even disable it. Update check [is performed](https://github.com/gouravkhunger/QuotesApp/blob/654cf8ccd2633ab343dad5b65b99c7839ecaf4d0/app/src/main/java/com/github/gouravkhunger/quotesapp/ui/QuotesActivity.kt#L80) without any "conditional".

I don't like setting an ultimatum, but as this repo here didn't see any activity for almost 2 years and I don't know if it is still active, this time I have to: without any response here within a month, the app will be removed from IzzyOnDroid at the end of that period. With a response, it depends of the planned action from your end of course. Thanks for understanding!

**Comment by gouravkhunger** [comment]
Hi @IzzySoft, that part is not a "self updater". It just checks if there are newer app versions available. And shows the option to open the latest github release page:

<img width="359" alt="image" src="https://github.com/user-attachments/assets/bef9fc8a-711c-4f95-b629-ce5183fb827f">

I agree the repo hasn't been active. I'm sorry I can't give a timeline on when I plan to do any refactors next.

**Comment by IzzySoft** [comment]
I guess there's no chance to make this opt-in in the near future?

**Comment by gouravkhunger** [comment]
On it. Will probably release something this weekend.

**Comment by IzzySoft** [comment]
Thanks! :star_struck:

**Comment by gouravkhunger** [comment]
@IzzySoft Released [`v2.1.2`](https://github.com/gouravkhunger/QuotesApp/releases/tag/2.1.2)

The setting is now disabled by default:

https://github.com/gouravkhunger/QuotesApp/blob/e9c184d6b90af963a4ac51251154d6535c1309ce/app/src/main/java/com/github/gouravkhunger/quotesapp/store/PreferenceStore.kt#L39-L47

https://github.com/gouravkhunger/QuotesApp/blob/e9c184d6b90af963a4ac51251154d6535c1309ce/app/src/main/java/com/github/gouravkhunger/quotesapp/ui/QuotesActivity.kt#L129

**Comment by IzzySoft** [comment]
Thanks! Is the toggle also explained as outlined above?

> Does it make the implications clear (e.g. that it bypasses the security checks performed in the IzzyOnDroid repo)?

**Comment by gouravkhunger** [comment]
Yes

<img width="312" alt="image" src="https://github.com/user-attachments/assets/e7ffbc31-f339-4e72-b42e-a0929e99ba48">

**Comment by IzzySoft** [comment]
Thanks! That makes clear where the updates are taken from. But where does that mention the implications (like bypassing the additional scans performed at e.g. IzzyOnDroid)? Maybe you could append something like

> [… please update from there], as e.g. additional security measures implemented there would be bypassed.

Always good to be as transparent as possible, to allow well informed decisions :wink:

**Comment by gouravkhunger** [comment]
@IzzySoft I understand that it is good to be transparent. Not denying updating the text. But, a new release for that minor text update doesn't seem enough tbh. I could do that when I implement some new features that are together worth a new release.

I see that the app version on your repo is still `2.1.1` while it's been a few days since `2.1.2` was released. Could you check why it didn't get picked? Thanks!

**Comment by IzzySoft** [comment]
> I could do that when I implement some new features that are together worth a new release.

That must suffice then. Hopefully it's not too far in the future, as I'll get daily warnings until then :see_no_evil:

> Could you check why it didn't get picked?

Sure. And easy answer:

> - 2023-07-13 UCM Tags => Static (last release 3/2022, last commit 10/2022)

It was "demoted" to monthly checks due to lack of activity. As there have not been at least 2 new releases within 3 months yet, it wasn't yet "promoted" back. Do you plan more frequent updates again? For the currently latest version, I've just manually triggered an update scan, which btw. yielded:

    ! repo/com.github.gouravkhunger.quotesapp_5.apk contains signature block blobs: 0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)

Can easily be solved with a minor addition to your `build.gradle`:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains. More details can be found e.g. here: [Ramping up security: additional APK checks are in place with the IzzyOnDroid repo](https://android.izzysoft.de/articles/named/iod-scan-apkchecks#blobs).

**Comment by IzzySoft** [comment]
@gouravkhunger where do we stand here with the self-updater? It's 3 months now. When I wrote it "must suffice", 6 weeks ago, I didn't expect nothing would happen for more than a month. Any ETA there? I still get the daily warning here :see_no_evil:

> a new release for that minor text update doesn't seem enough tbh.

Well, now you have "that minor text update" (did I miss the commit for that?) – and "that minor update to your `build.gradle` to remove a blob". Maybe that's worth a maintenance release? Considering it would free you from my nagging at well? :stuck_out_tongue_winking_eye:

**Comment by gouravkhunger** [comment]
@IzzySoft My bad! I've been overloaded with work since long. Hope this is better now? I've also added your fix to exclude the blob. Thanks!

<img width="263" alt="image" src="https://github.com/user-attachments/assets/e4a9665f-7d11-453b-ae6c-d37ba3e03184">

**Comment by IzzySoft** [comment]
Thanks! Yes, that looks excellent! Pulled the update in and, finally, could add the AppUpdater lib to your app's "green list" :star_struck: 

And no worries, I know what overloaded means. So I was not complaining, just sending a "friendly nudge" :wink:
