### ISSUE TITLE
Share button

### ISSUE THREAD

**Issue by gouravkhunger** [gouravkhunger/QuotesApp#5]
It would be great to see a share button on the bottom right of the cards:

![image](https://user-images.githubusercontent.com/46792249/135836047-1231223a-1535-480f-83b3-b492109681fe.png)

![image](https://user-images.githubusercontent.com/46792249/135836214-375de95d-e631-43dc-a8e9-13ee7e3f662a.png)

so that one can click on it and get a prompt to share an image of the card view to social media platforms. It would be nice to see a small text "Shared from QuotesApp made by Gourav."

Here's an example:

![Add a subheading](https://user-images.githubusercontent.com/46792249/135837158-d1e4df6c-122f-4e5c-95ca-b548b3ff8f00.png)

This is just a sample, fonts and color scheme isn't shown. This is just a gist of what I think would make the app super awesome :)

**Comment by pratik2315** [comment]
Hey!
I would like to work on this issue if its alright?
