### ISSUE TITLE
Update dependencies 

### ISSUE THREAD

**Issue by PranavVyas20** [gouravkhunger/QuotesApp#6]
Gson dependency is missing and some are not updated and are causing issues in code compilation
Can you assign me on this

**Comment by gouravkhunger** [comment]
Hello! Thanks for reaching out :)

Yes, you can work on updating the dependencies. Also, can you migrate from Groovy to KTS along side, since you are updating dependencies, it would be a good time to migrate to KTS version of `build.gradle` files :)

**Comment by PranavVyas20** [comment]
> Hello! Thanks for reaching out :)
> 
> Yes, you can work on updating the dependencies. Also, can you migrate from Groovy to KTS along side, since you are updating dependencies, it would be a good time to migrate to KTS version of `build.gradle` files :)

Sure will do that, also can you please label it as 'hactoberfest'

**Comment by gouravkhunger** [comment]
This repository is already eligible for Hackotberfest, you can go ahead :)
